### ISSUE TITLE
Modules removed if not updated when simplesamlphp is updated

### ISSUE THREAD

**Issue by forevermatt** [simplesamlphp/composer-module-installer#10]
I'm not sure whether to open this issue here or on the Composer repo, but if you have a composer.json that requires `simplesamlphp/simplesamlphp` as well as `simplesamlphp/composer-module-installer` and some simplesamlphp modules, running a `composer update` that updates `simplesamlphp/simplesamlphp` ends up removing any simplesamlphp modules that weren't updated at the same time.

The "missing" dependencies are still specified in the composer.lock file, and running a `composer install` adds them back to the vendor folder. But a `composer update` resulting in required packages being removed from the vendor folder seems like a bug.

You can replicate this (though it's not as simple an example as would be nice, see Note below) by installing the composer dependencies specified by [this composer.lock file](https://github.com/silinternational/ssp-base/blob/462881af7ffa90a36144ac69533c106ae32e2224/composer.lock), then putting [this revised composer.json](https://github.com/silinternational/ssp-base/blob/d3eb2be535bbca249caf3bdd4c56944e6ef6fed3/composer.json) in place and running a `composer update`.

The result is that simplesamlphp and the simplesamlphp modules with changes are updated, and the simplesamlphp modules without changes are removed (in the process of the simplesamlphp folder being updated).

**Note:** This composer file includes dependencies that rely on the [Composer Asset Plugin](https://github.com/fxpio/composer-asset-plugin) due to their use of the Yii framework, so you'll probably need to run to run something like `composer global require "fxp/composer-asset-plugin:^1.2.0"` before trying to replicate this issue.

**Comment by jaimeperez** [comment]
Hi @forevermatt,

This is indeed a bug, and an understandable one. Since we are moving files around in the file system, we are messing up what composer expects to have in place, and then when it removes a dependency before installing an updated one, all files moved there disappear. I still find it interesting, as if I recall correctly, I've seen composer warning about modified files before removing them, but since these are "new" files, it wouldn't surprise me either.

Anyway, the best way (and probably the only one) to fix this is to actually get rid of this installer and stop moving modules into the `modules` directory. That means SimpleSAMLphp also needs to stop expecting modules there. All of this is work in progress for 2.0 already, so I'm closing this issue here.

**Comment by forevermatt** [comment]
That makes sense, thanks Jaime. In the meantime, we've simply settled on [a shell script ](https://github.com/silinternational/ssp-base/blob/master/development/update-composer-deps.sh)that does the update (and re-install) as how we updated our composer dependencies for the repo where we experience this issue. Very manageable.

**Comment by jaimeperez** [comment]
Good that at least it's not breaking stuff for you and you were able to come around it. I reckon that workaround is unfortunate, but let's try to focus our efforts on having some well-thought code that avoids this kind of situation happening again. Thanks for the feedback @forevermatt!
