### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by corycollier** [simplesamlphp/composer-module-installer#2]
Just a thought, but would it be possible to specify directories for inclusion? For example, if I have `build`, `tests`, `src`, and `dist` directories, could I specify that I only wanted the `dist` directory to be copied into the `modules` directory?

**Comment by jaimeperez** [comment]
Ideally, our ultimate goal is to actually stop moving modules into the `modules` directory. Instead of that, SSP should receive fully qualified class names when dealing with modules, and provide the mechanisms necessary to use modules directly from the `vendor` directory. This is already work in progress for 2.0, so I'm closing this.
