### ISSUE TITLE
Require simplesamlphp/simplesamlphp

### ISSUE THREAD

**Issue by bradjones1** [simplesamlphp/composer-module-installer#3]
I ran into an interesting situation where I have a SSP module, installed with this package, but on fresh builds (e.g., on a CI server) the auth module was being installed prior to SSP being installed, and as such the module ended up in `[project]/modules` instead of under the `vendor/simplesaml...modules` directory.

Composer's dependency resolution is a bit of a black box to me but I do know it installs using required packages. I would think instead of requiring the various modules to be adjusted, we could just add the require statement to this package? It's not useful outside the context of a SSP install, so that would be a logical place to take care of it?

**Comment by jaimeperez** [comment]
Hi @bradjones1!

I'm afraid what you are suggesting is not possible. Currently, there are two ways to use SimpleSAMLphp:

* Installing it as a dependency of your own project using composer.
* Installing it manually (i.e. downloading the tarball, cloning it or even with the package manager from your favorite distro).

Your proposal works for the former, but not for the latter. If you install SimpleSAMLphp out of the tarball and try to install a module, then the module requires this installer, and if the installer requires SimpleSAMLphp, it will also be installed in `vendor/` as a dependency, which is not what we want.

The proper way to solve an issue like this is to solve the order of your requirements. Your `composer.json` should list SimpleSAMLphp as a dependency quite early if you are supposed to install modules.

**Comment by matrey** [comment]
FYI I had the same issue (on a project that also installed ssp through composer).
`composer install` would install the ssp modules in the project root under `modules`, rather than inside `vendor/simplesaml.../modules`

Adding `simplesamlphp/composer-module-installer` as a dependancy in the main project (in between ssp and the ssp modules) solved the issue.
Here is my composer.json:

```
    "require": {
        "php": ">=5.5.0",
        "simplesamlphp/simplesamlphp": "^1.14",
        "simplesamlphp/composer-module-installer": "~1.0", 
        "myprefix/simplesamlphp-module-mymodule": "*",
        ...
```

**Comment by jaimeperez** [comment]
Hi @matrey! Thanks for the feedback!

I believe the requirement for `simplesamlphp/composer-module-installer` is redundant here. Basically, if `myprefix/simplesamlphp-module-mymodule` already depends on it (as it should), then it doesn't really add anything to have it in your own requirements. The key part here would be listing `simplesamlphp/simplesamlphp` as a requirement itself, **before** the module.

**Comment by matrey** [comment]
Actually I have a couple of ssp modules that I keep in the same repository as the main project. I then use composer's "path" repository type to pull them in.

Main project composer.json:
```
    "require": {
        "php": ">=5.5.0",
        "simplesamlphp/simplesamlphp": "^1.14",
        "myprefix/simplesamlphp-module-mymodule": "*"
    },
    "repositories": [
        {
            "type": "path",
            "url": "./ssp-modules/mymodule",
            "options": {
                "symlink": false
            }
        }
    ]
```

Module's composer.json (`./ssp-modules/mymodule/composer.json`)
```
{
    "name": "myprefix/simplesamlphp-module-mymodule",
    "version": "1.0",
    "type": "simplesamlphp-module",
    "require": {
        "simplesamlphp/composer-module-installer": "~1.0",
        "predis/predis": "^1.0.3"
    }
}
```

The requirements' order seems fine. But with that setup, if I delete `composer.lock` and `vendor/` then `php composer.phar install --no-dev`, I do end up with a `modules` folder in my project's root ; not under `vendor/simple.../modules`.

After fiddling with the 2 `composer.json` files, it turns out my previous comment was incorrect. Indeed requiring `simplesamlphp/composer-module-installer` in the main project doesn't do much.
The only thing that worked was to require `simplesamlphp/simplesamlphp` in the ssp module, before `simplesamlphp/composer-module-installer` (as @bradjones1 suggested)

On https://getcomposer.org/doc/05-repositories.md I read "custom repository has priority over packagist".

So I think what's going on is:
- My ssp modules are handled first (because of the custom repository)
- As neither the ssp module nor `composer-module-installer` require `simplesamlphp/simplesamlphp`, they end up getting installed before ssp.
- Adding `simplesamlphp/simplesamlphp` as a dependancy in the custom ssp module forces ssp to be taken into account earlier on

**Final lesson being: beware of `composer` priorities when mixing Packagist and private repositories.**

**Comment by jaimeperez** [comment]
Hi @matrey!

That makes full sense, thanks a lot for debugging this further!

The main problem I see is that the obvious fix for this would be to include `simplesamlphp/simplesamlphp` as a dependency in `simplesamlphp/simplesamlphp-module-installer`.  However, that's not something we can do, since those installing the software from the tarballs won't have it registered in composer as _installed_, and then running composer will yield a second installation of `simplesamlphp/simplesamlphp` in the vendor directory, which is obviously not something we want.

So I'm afraid the only solution is to fix the composer configuration (per project) so that they fit with each particular needs.
